# Generated by Django 3.2.8 on 2021-10-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(choices=[('1', 'real_madrid'), ('2', 'barcelona'), ('3', 'manchester_united'), ('4', 'juventus'), ('5', 'cheslea'), ('6', 'paris_saint_german'), ('7', 'bayern_munich'), ('8', 'arsenal'), ('9', 'liverpool'), ('10', 'manchester_city')], max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': '10 Most Popular Football Clubs',
            },
        ),
    ]
