# Generated by Django 3.2.8 on 2021-10-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='club_name',
        ),
        migrations.AddField(
            model_name='club',
            name='arsenal',
            field=models.BooleanField(default=False, verbose_name='Arsenal'),
        ),
        migrations.AddField(
            model_name='club',
            name='barcelona',
            field=models.BooleanField(default=False, verbose_name='Barcelona'),
        ),
        migrations.AddField(
            model_name='club',
            name='bayern_munich',
            field=models.BooleanField(default=False, verbose_name='Bayern Munich'),
        ),
        migrations.AddField(
            model_name='club',
            name='cheslea',
            field=models.BooleanField(default=False, verbose_name='Cheslea'),
        ),
        migrations.AddField(
            model_name='club',
            name='juventus',
            field=models.BooleanField(default=False, verbose_name='Juventus'),
        ),
        migrations.AddField(
            model_name='club',
            name='liverpool',
            field=models.BooleanField(default=False, verbose_name='Liverpool'),
        ),
        migrations.AddField(
            model_name='club',
            name='manchester_city',
            field=models.BooleanField(default=False, verbose_name='Manchester City'),
        ),
        migrations.AddField(
            model_name='club',
            name='manchester_united',
            field=models.BooleanField(default=False, verbose_name='Manchester United'),
        ),
        migrations.AddField(
            model_name='club',
            name='paris_saint_german',
            field=models.BooleanField(default=False, verbose_name='Paris Saint German'),
        ),
        migrations.AddField(
            model_name='club',
            name='real_madrid',
            field=models.BooleanField(default=False, verbose_name='Real Madrid'),
        ),
    ]
