# Generated by Django 3.2.8 on 2021-10-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20211011_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='arsenal',
        ),
        migrations.RemoveField(
            model_name='club',
            name='barcelona',
        ),
        migrations.RemoveField(
            model_name='club',
            name='bayern_munich',
        ),
        migrations.RemoveField(
            model_name='club',
            name='cheslea',
        ),
        migrations.RemoveField(
            model_name='club',
            name='juventus',
        ),
        migrations.RemoveField(
            model_name='club',
            name='liverpool',
        ),
        migrations.RemoveField(
            model_name='club',
            name='manchester_city',
        ),
        migrations.RemoveField(
            model_name='club',
            name='manchester_united',
        ),
        migrations.RemoveField(
            model_name='club',
            name='paris_saint_german',
        ),
        migrations.RemoveField(
            model_name='club',
            name='real_madrid',
        ),
        migrations.AddField(
            model_name='club',
            name='club_name',
            field=models.CharField(choices=[('1', 'real_madrid'), ('2', 'barcelona'), ('3', 'manchester_united'), ('4', 'juventus'), ('5', 'cheslea'), ('6', 'paris_saint_german'), ('7', 'bayern_munich'), ('8', 'arsenal'), ('9', 'liverpool'), ('10', 'manchester_city')], max_length=20, null=True),
        ),
    ]
