# Generated by Django 3.2.8 on 2021-10-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20211011_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club1player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club1players', models.CharField(choices=[('1', 'karim_benzema'), ('2', 'eden_hazard'), ('3', 'marcelo_vieira'), ('4', 'gareth_bale'), ('5', 'eduardo_camavinga'), ('6', 'vini_jr'), ('7', 'ferland_mendy'), ('8', 'luka_modric'), ('9', 'david_alaba'), ('10', 'toni_kroos'), ('11', 'thibaut_courtois'), ('12', 'federico_valverde'), ('13', 'rodrygo'), ('14', 'isco'), ('15', 'marco_asensio'), ('16', 'casemiro'), ('17', 'dani_carvajal'), ('18', 'luka_jovic'), ('19', 'nacho'), ('20', 'lucas_vazquez'), ('21', 'eder_militao'), ('22', 'dani_ceballos'), ('23', 'mariano'), ('24', 'miguel_gutierrez'), ('25', 'jesus_vallejo'), ('26', 'andriy_lunin'), ('27', 'antonio_blanco'), ('28', 'toni_fuidias_ribera'), ('29', 'luis_federico_lopez'), ('30', 'sergio_santos')], max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Real Madrid Players',
            },
        ),
    ]
