# Generated by Django 3.2.8 on 2021-10-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_club2player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club2player',
            options={'verbose_name_plural': 'Barcelona Players'},
        ),
        migrations.AddField(
            model_name='club2player',
            name='club2players',
            field=models.CharField(choices=[('1', 'marc_andre'), ('2', 'neto'), ('3', 'inaki_pena'), ('4', 'sergino_dest'), ('5', 'gerard_pique'), ('6', 'ronald_aroujo'), ('7', 'clement_lenglet'), ('8', 'jordi_alba'), ('9', 'sergi_roberto'), ('10', 'oscar_mingueza'), ('11', 'samuel_umtiti'), ('12', 'eric_garcia'), ('13', 'sergio_busquets'), ('14', 'riqui_puig'), ('15', 'philippe_coutinho'), ('16', 'pedri'), ('17', 'frenkie_de_jong'), ('18', 'ousmane_demlele'), ('19', 'mempehis_depay'), ('20', 'ansu_fati'), ('21', 'yusuf_demir'), ('22', 'martin_braithwaite'), ('23', 'luuk_de_jong'), ('24', 'sergio_agğero')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='club1player',
            name='club1players',
            field=models.CharField(choices=[('1', 'karim_benzema'), ('2', 'eden_hazard'), ('3', 'marcelo_vieira'), ('4', 'gareth_bale'), ('5', 'eduardo_camavinga'), ('6', 'vini_jr'), ('7', 'ferland_mendy'), ('8', 'luka_modric'), ('9', 'david_alaba'), ('10', 'toni_kroos'), ('11', 'thibaut_courtois'), ('12', 'federico_valverde'), ('13', 'rodrygo'), ('14', 'isco'), ('15', 'marco_asensio'), ('16', 'casemiro'), ('17', 'dani_carvajal'), ('18', 'luka_jovic'), ('19', 'nacho'), ('20', 'lucas_vazquez'), ('21', 'eder_militao'), ('22', 'dani_ceballos'), ('23', 'mariano'), ('24', 'miguel_gutierrez'), ('25', 'jesus_vallejo'), ('26', 'andriy_lunin'), ('27', 'antonio_blanco'), ('28', 'toni_fuidias_ribera'), ('29', 'luis_federico_lopez'), ('30', 'sergio_santos')], max_length=24, null=True),
        ),
    ]
